theme = "tokyonight_moon"

[editor]
auto-completion = true
auto-format = true
bufferline = "always"
color-modes = true
completion-replace = false
completion-trigger-len = 2
continue-comments = true
cursorline = true
end-of-line-diagnostics = "hint"
idle-timeout = 250
insert-final-newline = true
line-number = "relative"
mouse = false
popup-border = "all"
preview-completion-insert = false
rulers = [160]
scrolloff = 8
shell = ["fish", "-c"]
text-width = 160

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 3000
focus-lost = true

[editor.file-picker]
git-exclude = true
git-global = true
git-ignore = true
hidden = false
max-depth = 8

[editor.gutters]
layout = ["diagnostics", "diff", "line-numbers"]

[editor.gutters.line-numbers]
min-width = 1

[editor.indent-guides]
character = "▏" # "▏" "┊", "┆"
render = true
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "warning"
max-diagnostics = 20
max-wrap = 80
other-lines = "info"

[editor.lsp]
auto-signature-help = true
display-color-swatches = true
display-inlay-hints = true
display-messages = true
display-signature-help-docs = true
enable = true
snippets = true

[editor.search]
smart-case = true
wrap-around = true

[editor.smart-tab]
enable = true
supersede-menu = true

[editor.soft-wrap]
enable = false

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.statusline]
center = ["file-name"]
left = [
  "file-modification-indicator",
  "mode",
  "read-only-indicator",
  "version-control",
]
right = [
  "diagnostics",
  "file-encoding",
  "file-line-ending",
  "file-type",
  "position",
  "register",
  "selections",
  "spinner",
  "workspace-diagnostics",
]
separator = "│"
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"

[editor.whitespace.characters]
nbsp = "⍽"
newline = "⏎"
nnbsp = "␣"
space = "·"
tab = "→"
tabpad = "·"

[editor.whitespace.render]
nbsp = "all"
newline = "none"
nnbsp = "all"
space = "all"
tab = "all"

[keys.insert]
A-h = "move_char_left"
A-j = "move_line_down"
A-k = "move_line_up"
A-l = "move_char_right"

[keys.normal]
'C-[' = ":buffer-previous"
'C-]' = ":buffer-next"
C-d = "half_page_down"
C-u = "half_page_up"
C-l = ":fmt"
C-n = ["move_line_down", "scroll_down"]
C-p = ["move_line_up", "scroll_up"]
C-q = ":buffer-close"
esc = ["collapse_selection", "keep_primary_selection"]
H = "goto_line_start"
L = "goto_line_end"
